# Generated by Django 3.0.5 on 2021-03-05 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todocompleteornot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='band name')),
            ],
            options={
                'verbose_name': 'Is completed or not?',
            },
        ),
        migrations.CreateModel(
            name='Todotasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Task')),
                ('created', models.DateTimeField(verbose_name='Created')),
                ('due_on', models.DateTimeField(verbose_name='Due on')),
                ('owner', models.CharField(max_length=100, verbose_name='Owner')),
                ('mark', models.CharField(max_length=100, verbose_name='Mark')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Todos', to='main.Todocompleteornot', verbose_name='band name')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
